

---
argocd_helm_chart_version: "9.1.2"
argocd_root_app_repo_url: "https://github.com/jangroth/homekube-apps.git"
argocd_root_app_path: "applications"
argocd_root_app_target_revision: "HEAD"

cilium_version: "1.18.2"

containerd_version: "2.1.4"

etcdctl_version: "3.6.4"

kube_bench_version: "0.13.0"

kubernetes_version: "1.35"

longhorn_version: "1.9.1"

ssh_username: "homekube"

system_arch: "linux-arm64"
system_arch_v2: "linux_arm64"
