---
- name: Add Tailscale's package signing key
  shell: |
    curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg | tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
  args:
    creates: /usr/share/keyrings/tailscale-archive-keyring.gpg

- name: Add Tailscale repository
  shell: |
    curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list | tee /etc/apt/sources.list.d/tailscale.list
  args:
    creates: /etc/apt/sources.list.d/tailscale.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Tailscale
  apt:
    pkg:
      - tailscale
    state: present
